const $=id=>document.getElementById(id);let parentId=null,operationId=null;
const states={QUEUED:"В очереди",RUNNING:"В работе",COMPLETED:"Готово",READY_FOR_REVIEW:"Готово к проверке",FAILED:"Нужна доработка",WAITING_PROVIDER:"Ожидает подключения или модели",AWAITING_INPUT:"Нужно уточнение",CANCELLED:"Отменено"};
function notice(text,error=false){$("notice").textContent=text;$("notice").className=error?"error":"success";}
async function api(path,body){const opt={headers:{"X-Telok-Client":"dashboard"}};if(body!==undefined){opt.method="POST";if(body instanceof FormData)opt.body=body;else{opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(body);}}const r=await fetch(path,opt);const v=await r.json();if(!r.ok)throw Error(typeof v.detail==="string"?v.detail:"Запрос не выполнен");return v;}
function action(id,fn){$(id).onclick=async()=>{$(id).disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{$(id).disabled=false;}};}
async function setup(){const s=await api("/api/assistant/setup"),c=s.chatgpt;$("plan-status").textContent=c.verified?"● ChatGPT Plan: проверено":c.connected?"● Авторизация сохранена. Проверьте модель.":"○ ChatGPT ещё не подключён";if(c.last_error&&c.last_error.code)notice("Последняя попытка входа: "+c.last_error.code+". Начните подключение заново.",true);$("credits").checked=c.credits_block_confirmed;$("route").value=c.route;if(c.model)$("plan-model").replaceChildren(new Option(c.model,c.model));$("local-url").value=s.local.url;$("local-model").value=s.local.model;$("telegram-status").textContent=s.telegram.configured?"● @"+s.telegram.username:"○ Бот ещё не подключён";$("tg-stopped").checked=!!s.telegram.old_poller_stopped;if(s.telegram.owner_id)$("tg-owner").value=s.telegram.owner_id;}
async function projects(){const v=await api("/api/assistant/projects");$("project").replaceChildren(...v.map(p=>new Option(p.name,p.id)));const personal=v.find(p=>p.brand.kind==="personal");if(personal)$("project").value=personal.id;}
async function tasks(){const v=await api("/api/assistant/tasks");$("tasks").replaceChildren();if(!v.length){$("tasks").textContent="Здесь появятся ваши задачи.";return;}for(const t of v){const d=document.createElement("div");d.className="task";const h=document.createElement("strong");h.textContent=t.payload.prompt.slice(0,120);const p=document.createElement("p");p.textContent=(states[t.status]||t.status)+" · "+t.created_at.slice(0,16).replace("T"," ");const b=document.createElement("button");b.textContent="Открыть";b.className="secondary";b.onclick=()=>show(t.id).catch(e=>notice(e.message,true));d.append(h,p,b);$("tasks").append(d);}}
function node(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn){const b=node("button",text,"secondary");b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}};return b;}
async function show(id){const t=await api("/api/assistant/tasks/"+id);$("result-card").hidden=false;const root=$("result");root.replaceChildren(node("p",(states[t.status]||t.status)+" · "+(t.result.media_status||t.result.stage||"")),node("p",t.result.text||"Задача выполняется."));const base="/api/assistant/tasks/"+id;
const intelligence=t.result.provider?t.result:t.result.research;if(intelligence&&intelligence.provider)root.append(node("p","Модель: "+intelligence.provider+" / "+intelligence.model+(intelligence.fallback?" · использован локальный резервный маршрут":"")));if(t.result.media_note)root.append(node("p",t.result.media_note));if(t.result.media_error)root.append(node("p",t.result.media_error));
if(t.result.concepts){t.result.concepts.ideas.forEach((idea,i)=>{const card=node("div",null,"scene");card.append(node("strong",(i+1)+". "+idea.title),node("p",idea.hook),node("p",idea.visual),button("Выбрать идею",async()=>{const r=await api("/api/assistant/tasks",{prompt:"Подготовь производственный пакет по выбранной идее, сохрани исходный бриф.",project_id:t.project_id,parent_id:id,selected_idea:i,mode:"CONTENT_CAMPAIGN",operation_id:crypto.randomUUID()});notice("Принято: "+r.id);await tasks();}));root.append(card);});}
if(t.result.production){root.append(node("h3",t.result.production.title));for(const scene of t.result.production.scenes){const card=node("div",null,"scene");card.append(node("strong",scene.scene_id+" · "+scene.duration_seconds+" сек"),node("p",scene.purpose),node("p",scene.prompt));const file=node("input");file.type="file";file.accept="video/mp4";card.append(file,button("Загрузить клип",async()=>{if(!file.files[0])throw Error("Выберите MP4.");const fd=new FormData();fd.append("file",file.files[0]);await api(base+"/scenes/"+encodeURIComponent(scene.scene_id)+"/import",fd);notice("Клип сохранён: "+scene.scene_id);}),button("Создать в Seedance",async()=>{await api(base+"/scenes/"+encodeURIComponent(scene.scene_id)+"/generate",{});notice("Заказ поставлен в очередь.");}),button("Править эту сцену",async()=>{parentId=id;window.editSceneIds=[scene.scene_id];$("project").value=t.project_id;$("mode").value="EDIT_ARTIFACT";$("parent").textContent="Правка только "+scene.scene_id;$("prompt").focus();}));root.append(card);}root.append(button("Собрать ролик",async()=>{await api(base+"/montage",{});notice("Монтаж поставлен в очередь. Обновите результат после завершения.");}),button("Проверить кадры",async()=>{await api(base+"/video-qa",{});notice("Проверка поставлена в очередь.");}));const jobs=await api(base+"/media");if(jobs.length)root.append(node("p",jobs.map(j=>j.scene_id+": "+j.status).join(" · ")));}
if(t.result.video_asset_id){const v=node("video");v.controls=true;v.preload="metadata";v.src=base+"/video";root.append(v);const l=node("a","Скачать MP4");l.href=v.src;l.download="telok-video.mp4";root.append(l);}
if(t.result.qa)root.append(node("p","Проверка пакета: "+t.result.qa.summary));if(t.result.video_qa)root.append(node("p","Проверка видео: "+JSON.stringify(t.result.video_qa)));
$("result-actions").replaceChildren(button("Продолжить / внести правку",async()=>{parentId=id;window.editSceneIds=[];$("project").value=t.project_id;$("parent").textContent="Продолжение задачи "+id;$("prompt").focus();}),button("Отменить",async()=>{await api(base+"/cancel",{});await tasks();}),button("Обновить результат",()=>show(id)));const link=node("a","Скачать полный результат");link.href=base+"/export";$("result-actions").append(link);}
action("connect",async()=>{const r=await api("/api/assistant/chatgpt/connect",{});window.location.assign(r.url);});
action("disconnect",async()=>{const r=await api("/api/assistant/chatgpt/disconnect",{});await setup();notice(r.remote_revocation_confirmed?"Подключение отключено.":"Локальные credentials удалены. Отзыв на сервере не подтверждён; проверьте ChatGPT Settings.");});
action("models",async()=>{const m=await api("/api/assistant/models/plan");$("plan-model").replaceChildren(...m.map(v=>new Option(v.name,v.id)));});
action("save-plan",async()=>{await api("/api/assistant/config",{plan_model:$("plan-model").value,credits_block_confirmed:$("credits").checked});notice("Настройки сохранены.");});
action("check",async()=>{await api("/api/assistant/config",{plan_model:$("plan-model").value,credits_block_confirmed:$("credits").checked});const r=await api("/api/assistant/chatgpt/check",{});notice(r.text);await setup();});
action("save-route",async()=>{await api("/api/assistant/config",{route:$("route").value,local_url:$("local-url").value,local_model:$("local-model").value});notice("Маршрут сохранён.");});
action("local-models",async()=>{await api("/api/assistant/config",{local_url:$("local-url").value});const m=await api("/api/assistant/models/local");if(m[0])$("local-model").value=m[0].id;notice("Локальный каталог: "+m.map(v=>v.name).join(", "));});
action("save-telegram",async()=>{await api("/api/assistant/telegram",{token:$("tg-token").value,owner_id:Number($("tg-owner").value),old_poller_stopped:$("tg-stopped").checked});$("tg-token").value="";await setup();await projects();notice("Бот сохранён и запущен. Напишите ему /start в Telegram.");});
action("submit",async()=>{const docs=[],file=$("document").files[0];if(file){const fd=new FormData();fd.append("file",file);docs.push(await api("/api/assistant/document",fd));}const refs=[],photo=$("reference").files[0];if(photo){const fd=new FormData();fd.append("file",photo);refs.push((await api("/api/assistant/projects/"+$("project").value+"/reference",fd)).asset_id);}operationId=operationId||crypto.randomUUID();const t=await api("/api/assistant/tasks",{prompt:$("prompt").value,project_id:$("project").value,mode:$("mode").value,parent_id:parentId,operation_id:operationId,documents:docs,reference_asset_ids:refs,edit_scene_ids:window.editSceneIds||[]});operationId=null;notice("Задача принята: "+t.id);await tasks();});
action("reset",async()=>{parentId=null;operationId=null;$("parent").textContent="";$("prompt").value="";$("document").value="";$("reference").value="";window.editSceneIds=[];});action("refresh",tasks);
Promise.all([setup(),projects(),tasks()]).catch(e=>notice(e.message,true));setInterval(()=>tasks().catch(()=>{}),10000);
action("create-project",async()=>{const p=await api("/api/assistant/projects",{name:$("project-name").value});await projects();$("project").value=p.id;notice("Проект создан.");});
action("save-seedance",async()=>{await api("/api/assistant/seedance/config",{api_key:$("seed-key").value,model:$("seed-model").value,enabled:$("seed-enabled").checked,download_domains:$("seed-domains").value.split(",").map(v=>v.trim()).filter(Boolean)});$("seed-key").value="";notice("Настройки Seedance сохранены.");});
